[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "everything-i-know"
authors = [{name = "Robb Manes", email = "robbmanes@protonmail.com"}]
dynamic = ["version", "description"]
